<?php

/**
 * @file
 * Default template for HTML Mail
 *
 * DO NOT EDIT THIS FILE. Copy it to your theme directory, and edit the copy.
 *
 * ========================================================= Begin instructions.
 *
 * When formatting an email message with a given $module and $key, [1]HTML
 * Mail will use the first template file it finds from the following list:
 *  1. htmlmail--$module--$key.tpl.php
 *  2. htmlmail--$module.tpl.php
 *  3. htmlmail.tpl.php
 *
 * For each filename, [2]HTML Mail looks first in the chosen Email theme
 * directory, then in its own module directory, before proceeding to the
 * next filename.
 *
 * For example, if example_module sends mail with:
 * drupal_mail("example_module", "outgoing_message" ...)
 *
 *
 * the possible template file names would be:
 *  1. htmlmail--example_module--outgoing_message.tpl.php
 *  2. htmlmail--example_module.tpl.php
 *  3. htmlmail.tpl.php
 *
 * Template files are cached, so remember to clear the cache by visiting
 * admin/config/development/performance after changing any .tpl.php files.
 *
 * The following variables available in this template:
 *
 * $body
 *        The message body text.
 *
 * $module
 *        The first argument to [3]drupal_mail(), which is, by convention,
 *        the machine-readable name of the sending module.
 *
 * $key
 *        The second argument to [4]drupal_mail(), which should give some
 *        indication of why this email is being sent.
 *
 * $message_id
 *        The email message id, which should be equal to
 *        "{$module}_{$key}".
 *
 * $headers
 *        An array of email (name => value) pairs.
 *
 * $from
 *        The configured sender address.
 *
 * $to
 *        The recipient email address.
 *
 * $subject
 *        The message subject line.
 *
 * $body
 *        The formatted message body.
 *
 * $language
 *        The language object for this message.
 *
 * $params
 *        Any module-specific parameters.
 *
 * $template_name
 *        The basename of the active template.
 *
 * $template_path
 *        The relative path to the template directory.
 *
 * $template_url
 *        The absolute URL to the template directory.
 *
 * $theme
 *        The name of the Email theme used to hold template files. If the
 *        [5]Echo module is enabled this theme will also be used to
 *        transform the message body into a fully-themed webpage.
 *
 * $theme_path
 *        The relative path to the selected Email theme directory.
 *
 * $theme_url
 *        The absolute URL to the selected Email theme directory.
 *
 * $debug
 *        TRUE to add some useful debugging info to the bottom of the
 *        message.
 *
 * Other modules may also add or modify theme variables by implementing a
 * MODULENAME_preprocess_htmlmail(&$variables) [6]hook function.
 *
 * References
 *
 * 1. http://drupal.org/project/htmlmail
 * 2. http://drupal.org/project/htmlmail
 * 3. http://api.drupal.org/api/drupal/includes--mail.inc/function/drupal_mail/7
 * 4. http://api.drupal.org/api/drupal/includes--mail.inc/function/drupal_mail/7
 * 5. http://drupal.org/project/echo
 * 6. http://api.drupal.org/api/drupal/modules--system--theme.api.php/function/hook_preprocess_HOOK/7
 *
 * =========================================================== End instructions.
 */
  $template_name = basename(__FILE__);
  $current_path = realpath(NULL);
  $current_len = strlen($current_path);
  $template_path = realpath(dirname(__FILE__));
  if (!strncmp($template_path, $current_path, $current_len)) {
    $template_path = substr($template_path, $current_len + 1);
  }
  $template_url = url($template_path, array('absolute' => TRUE));
?>
<div class="htmlmail-body send-a-friend">
  <table border="0" cellpadding="0" cellspacing="0" width="100%" style="color: #4d4d4d;font-family: 'IBM Plex Sans', 'Helvetica Neue', Arial, sans-serif;font-size: 14px;font-weight: 300;line-height: 18px; margin:50px auto 0; max-width:800px;">
          <tr>
              <th>
                <table border="0" cellpadding="0" cellspacing="0"  style="">
                  <tr>
                    <th>
                          <table border="0" cellpadding="0" cellspacing="0"  style=" margin:0 0 0;  text-align: left;">
                            <thead>
                            <tr>
                              <th><img src="http://sparklelabs.opensenselabs.com/sites/all/themes/spklab/images/sl_logo_knockout.png" style="background-color:#34C8B6; margin-top: 30px; margin-bottom: 15px;"></th>
                            </tr>
                            <tr>
                              <th style="font-size: 19px; line-height: 28px; font-weight: 300; color: #EB4848; text-align: justify;">
                          <?php echo $params["message"]; ?>

                              </th>
                            </tr>
                          </thead>
                        </table>


                        <table border="0" cellpadding="0" cellspacing="0"  style=" margin:20px 0 0; width:100%; text-align: left;">
                          <tr>
                            <th>
                              <img src="<?php echo $params["img_url"]; ?>" style=" width:100%;">
                            </th>
                          </tr>
                        </table>


                        <table border="0" cellpadding="0" cellspacing="0"  style=" margin:20px 0 0; width:100%; text-align: left;">
                          <tr>
                            <th style="width: 50%; max-width: 400px">
                              <h2 style="font-size:25px; font-weight:300;"><?php echo $params["page_title"]; ?></h2>
                              <div style="font-weight: 300; text-align: justify; line-height: 24px;"><?php echo $params["page_desc"]; ?></div>
                            </th>
                            <th style="width: 50%; max-width: 400px; vertical-align: top; padding: 0 0 0 40px;" ><a href="<?php echo $params["page_url"] . "?utm_source=email-traffic&utm_medium=send-a-friend"; ?>" style=" margin-top:15px; max-width:400px; border-radius:6px; margin-top: 68px; background-color: #34C8B6;color: #fff;padding: 16px 28px;display: block;font-size: 16px;text-align: center; text-decoration: none;">Check it out</a></th>
                          </tr>
                        </table>

                         <table border="0" cellpadding="0" cellspacing="0"  style=" margin:10px 0 ; width:100%; text-align: left;">
                           <tr>
                             <th style ="display: flex;text-transform: uppercase;">

                               <?php
                               echo $params["category"]; ?>
                             </th>
                           </tr>
                         </table>

                         <table border="0" cellpadding="0" cellspacing="0"  style=" margin:30px 0 0; width:100%; text-align: left; padding: 140px 60px 50px; background:url(http://sparklelabs.opensenselabs.com/sites/all/themes/spklab/images/placeholder.png) center no-repeat;">
                           <tr>
                             <th>
                              <p style="font-weight: normal; text-align: justify;">This is a standard paragraph. Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <strong>Ut enim ad minim veniam,</strong> quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                             </th>
                           </tr>
                         </table>

                         <table align="right" border="0" cellpadding="0" cellspacing="0"  style=" margin:50px 0 0; width:100%; text-align: right;  padding: 0px 0px 20px;">
                           <tr>
                             <th>
                               <a href="#" style="display: inline-block; margin-left: 12px; text-decoration: none;"><img style="width:50px; background: #34C8B6;" src="http://sparklelabs.opensenselabs.com/sites/all/themes/spklab/images/socialicon_fb_knockout_white.png"></a>
                               <a href="#" style="display: inline-block;  margin-left: 12px; text-decoration: none;"><img style="width:50px; background: #34C8B6;" src="http://sparklelabs.opensenselabs.com/sites/all/themes/spklab/images/socialicon_in_knockout_white.png"></a>
                               <a href="#" style="display: inline-block;  margin-left: 12px; text-decoration: none;"><img style="width:50px; background: #34C8B6;" src="http://sparklelabs.opensenselabs.com/sites/all/themes/spklab/images/socialicon_pn_knockout_white.png"></a>
                               <a href="#" style="display: inline-block;  margin-left: 12px; text-decoration: none;"><img style="width:50px; background: #34C8B6;" src="http://sparklelabs.opensenselabs.com/sites/all/themes/spklab/images/socialicon_tw_knockout_white.png"></a>
                             </th>
                           </tr>
                           <tr>
                             <th><span style=" display:block; text-align:left; font-size: 10px; font-weight: normal;">© 2018 Sparkle Labs.</span></th>
                           </tr>
                         </table>

                  </th>
                  </tr>
                </table>

            </th>
          </tr>
      </table>

</div>
<?php if ($debug):
  $module_template = "htmlmail--$module.tpl.php";
  $message_template = "htmlmail--$module--$key.tpl.php";
?>
<hr />


<div class="htmlmail-debug">
  <dl><dt><p>
    To customize this message:
  </p></dt><dd><ol><li><p><?php if (empty($theme)): ?>
    Visit <u>admin/config/system/htmlmail</u>
    and select a theme to hold your custom email template files.
  </p></li><li><p><?php elseif (empty($theme_path)): ?>
    Visit <u>admin/appearance</u>
    to enable your selected
    <u><?php echo drupal_ucfirst($theme); ?></u> theme.
  </p></li><li><?php endif;
if ("$template_path/$template_name" == "$theme_path/$message_template"): ?><p>
    Edit your<br />
    <code><?php echo "$template_path/$template_name"; ?></code>
    <br />file.
  </p></li><li><?php
else:
  if (!file_exists("$theme_path/htmlmail.tpl.php")): ?><p>
    Copy<br />
    <code><?php echo "$module_path/htmlmail.tpl.php"; ?></code>
    <br />to<br />
    <code><?php echo "$theme_path/htmlmail.tpl.php"; ?></code>
  </p></li><li><?php
  endif;
  if (!file_exists("$theme_path/$module_template")): ?><p>
    For module-specific customization, copy<br />
    <code><?php echo "$module_path/htmlmail.tpl.php"; ?></code>
    <br />to<br />
    <code><?php echo "$theme_path/$module_template"; ?></code>
  </p></li><li><?php
  endif;
  if (!file_exists("$theme_path/$message_template")): ?><p>
    For message-specific customization, copy<br />
    <code><?php echo "$module_path/htmlmail.tpl.php"; ?></code>
    <br />to<br />
    <code><?php echo "$theme_path/$message_template"; ?></code>
  </p></li><li><?php endif; ?><p>
    Edit the copied file.
  </p></li><li><?php
endif; ?><p>
    Send a test message to make sure your customizations worked.
  </p></li><li><p>
    If you think your customizations would be of use to others,
    please contribute your file as a feature request in the
    <a href="http://drupal.org/node/add/project-issue/htmlmail">issue queue</a>.
  </p></li></ol></dd><?php if (!empty($params)): ?><dt><p>
    The <?php echo $module; ?> module sets the <u><code>$params</code></u>
    variable.  For this message,
  </p></dt><dd><p><code><pre>
$params = <?php echo check_plain(print_r($params, 1)); ?>
  </pre></code></p></dd><?php endif; ?></dl>
</div>
<?php endif;
